version: '3'
services:
  jupyter-notebook:
    build: 
      context: .
      dockerfile: scipy-notebook.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - /workspace/jupyter-notebook/src:/home/jovyan/work