version: '3'
services:
  jupyter-notebook:
    image: jupyter/scipy-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes